### ISSUE TITLE
Python3.8.10 on Linux throws this, no other version does?

### ISSUE THREAD

**Issue by emuskardin** [DES-Lab/AALpy#61]
```
Traceback (most recent call last):
  File "git_learning.py", line 1, in <module>
    from aalpy.learning_algs import run_Lstar
  File "/mnt/c/Users/muskardine/PycharmProjects/git_learning/myvenv/lib/python3.8/site-packages/aalpy/__init__.py", line 1, in <module>
    from .automata import (
  File "/mnt/c/Users/muskardine/PycharmProjects/git_learning/myvenv/lib/python3.8/site-packages/aalpy/automata/__init__.py", line 8, in <module>
    from .Sevpa import Sevpa, SevpaState, SevpaAlphabet, SevpaTransition
  File "/mnt/c/Users/muskardine/PycharmProjects/git_learning/myvenv/lib/python3.8/site-packages/aalpy/automata/Sevpa.py", line 87, in <module>
    class Sevpa(Automaton):
  File "/mnt/c/Users/muskardine/PycharmProjects/git_learning/myvenv/lib/python3.8/site-packages/aalpy/automata/Sevpa.py", line 93, in Sevpa
    def __init__(self, initial_state: SevpaState, states: list[SevpaState]):
TypeError: 'type' object is not subscriptable
```

**Comment by emuskardin** [comment]
@zwergziege 
https://stackoverflow.com/questions/75202610/typeerror-type-object-is-not-subscriptable-python

You see, the absence of types would be superior to such trivial mistakes... well of course List[x] is fundamentally different to list[x]
